//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.16.0
//     from Assets/_Project/_FighterBase/Input Actions/FighterController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/_Project/_FighterBase/Input Actions/FighterController.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @FighterController: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @FighterController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""FighterController"",
    ""maps"": [
        {
            ""name"": ""StandingActions"",
            ""id"": ""884b88f3-1202-46ac-95f7-347d752e473f"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""761227bf-8dbe-457f-b3df-75dcc6e07db3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Value"",
                    ""id"": ""a0f2876a-0c51-42bd-bb4b-bc1e3be69b40"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""29957fa6-5c9f-46a9-be7f-6a8445de21da"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Light"",
                    ""type"": ""Button"",
                    ""id"": ""07633f2c-98fc-4ef5-a746-6ffbbfc61125"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Medium"",
                    ""type"": ""Button"",
                    ""id"": ""2b6ec556-0454-48c9-8b60-4a827d574f2d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heavy"",
                    ""type"": ""Button"",
                    ""id"": ""b2d05cb2-ae8f-4438-9e0f-c417144f6633"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""da818f1b-ef65-42ed-a0c1-bea23de71175"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Dpad"",
                    ""id"": ""db45512b-8d34-4067-a91d-1bf6b9ebbeab"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e41d721f-c9ab-4f91-96b3-54e271336318"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e400bafe-8726-4a38-bcf9-e11cf2d4464e"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftStick"",
                    ""id"": ""ca708fc2-da40-4180-8442-919b753d08a6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f92636e4-3974-4c06-9ac9-7eee8ab5b280"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""485f48c9-0b16-4f52-b639-27692ea32e90"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""e87bea9b-38ea-49d1-b3b7-1b170ce150a8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b233baea-9fed-4f0e-a498-55292a820751"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""97aa1806-6ef8-4066-a5b7-2bb93cc08d1f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""354a2116-dee7-49d3-9208-95ec3f7b669d"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bce4ef2a-669e-43ab-9c4c-4fec3b8cf2eb"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ca13c86-933a-476f-8689-f32ec8a28e37"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Medium"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0135fa41-599b-43b7-bf5e-0824d775e111"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Medium"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8baf7e79-980d-46a5-9c5b-798530bf7eba"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2cc071b-b608-4462-a9e7-e69171976558"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbab2baf-3951-439b-bf16-202c50e18917"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1377d7f6-eb59-43a2-ba67-1e25b6ba4f37"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a0c43b6-c15d-4e43-a0ec-206c868c8adf"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e78cca7a-aa12-4314-bb4a-4c34e9cb48d2"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5e6ed6d-3b97-4b0e-a00d-d4a45298847d"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c189f1a-45c2-4260-b9ca-ea7ec68d74b1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""551b58e5-1dd0-4f12-b505-d982f7ced686"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""161a15ef-8be4-4e39-9df6-c77eef6a127e"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CrouchingActions"",
            ""id"": ""d22a0821-482a-430a-a8c2-849791785c74"",
            ""actions"": [
                {
                    ""name"": ""CrouchLight"",
                    ""type"": ""Button"",
                    ""id"": ""03dc305f-9fe2-41b6-917c-93e30af5b38f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CrouchMedium"",
                    ""type"": ""Button"",
                    ""id"": ""c65e516c-8744-4659-a870-4dfa7ddcfb72"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CrouchHeavy"",
                    ""type"": ""Button"",
                    ""id"": ""1b1a37ca-6d1a-42c7-b6df-d065f33d9c96"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""75696736-3eea-484d-abef-32b4467a54d1"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CrouchLight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8821051a-2a3a-4660-99de-30e426233fa8"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CrouchLight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c662543-0601-4101-a81a-e794523d7bf5"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CrouchMedium"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e8e2519-6c12-4b85-b00f-5ee914596875"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CrouchMedium"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d84a416-a6f2-46ab-a79c-1916d11f9f9c"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CrouchHeavy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61020ea5-2045-44af-a8e9-325ede3b7b88"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CrouchHeavy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // StandingActions
        m_StandingActions = asset.FindActionMap("StandingActions", throwIfNotFound: true);
        m_StandingActions_Movement = m_StandingActions.FindAction("Movement", throwIfNotFound: true);
        m_StandingActions_Jump = m_StandingActions.FindAction("Jump", throwIfNotFound: true);
        m_StandingActions_Crouch = m_StandingActions.FindAction("Crouch", throwIfNotFound: true);
        m_StandingActions_Light = m_StandingActions.FindAction("Light", throwIfNotFound: true);
        m_StandingActions_Medium = m_StandingActions.FindAction("Medium", throwIfNotFound: true);
        m_StandingActions_Heavy = m_StandingActions.FindAction("Heavy", throwIfNotFound: true);
        m_StandingActions_Dash = m_StandingActions.FindAction("Dash", throwIfNotFound: true);
        // CrouchingActions
        m_CrouchingActions = asset.FindActionMap("CrouchingActions", throwIfNotFound: true);
        m_CrouchingActions_CrouchLight = m_CrouchingActions.FindAction("CrouchLight", throwIfNotFound: true);
        m_CrouchingActions_CrouchMedium = m_CrouchingActions.FindAction("CrouchMedium", throwIfNotFound: true);
        m_CrouchingActions_CrouchHeavy = m_CrouchingActions.FindAction("CrouchHeavy", throwIfNotFound: true);
    }

    ~@FighterController()
    {
        UnityEngine.Debug.Assert(!m_StandingActions.enabled, "This will cause a leak and performance issues, FighterController.StandingActions.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_CrouchingActions.enabled, "This will cause a leak and performance issues, FighterController.CrouchingActions.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // StandingActions
    private readonly InputActionMap m_StandingActions;
    private List<IStandingActionsActions> m_StandingActionsActionsCallbackInterfaces = new List<IStandingActionsActions>();
    private readonly InputAction m_StandingActions_Movement;
    private readonly InputAction m_StandingActions_Jump;
    private readonly InputAction m_StandingActions_Crouch;
    private readonly InputAction m_StandingActions_Light;
    private readonly InputAction m_StandingActions_Medium;
    private readonly InputAction m_StandingActions_Heavy;
    private readonly InputAction m_StandingActions_Dash;
    /// <summary>
    /// Provides access to input actions defined in input action map "StandingActions".
    /// </summary>
    public struct StandingActionsActions
    {
        private @FighterController m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public StandingActionsActions(@FighterController wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "StandingActions/Movement".
        /// </summary>
        public InputAction @Movement => m_Wrapper.m_StandingActions_Movement;
        /// <summary>
        /// Provides access to the underlying input action "StandingActions/Jump".
        /// </summary>
        public InputAction @Jump => m_Wrapper.m_StandingActions_Jump;
        /// <summary>
        /// Provides access to the underlying input action "StandingActions/Crouch".
        /// </summary>
        public InputAction @Crouch => m_Wrapper.m_StandingActions_Crouch;
        /// <summary>
        /// Provides access to the underlying input action "StandingActions/Light".
        /// </summary>
        public InputAction @Light => m_Wrapper.m_StandingActions_Light;
        /// <summary>
        /// Provides access to the underlying input action "StandingActions/Medium".
        /// </summary>
        public InputAction @Medium => m_Wrapper.m_StandingActions_Medium;
        /// <summary>
        /// Provides access to the underlying input action "StandingActions/Heavy".
        /// </summary>
        public InputAction @Heavy => m_Wrapper.m_StandingActions_Heavy;
        /// <summary>
        /// Provides access to the underlying input action "StandingActions/Dash".
        /// </summary>
        public InputAction @Dash => m_Wrapper.m_StandingActions_Dash;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_StandingActions; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="StandingActionsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(StandingActionsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="StandingActionsActions" />
        public void AddCallbacks(IStandingActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_StandingActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_StandingActionsActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Light.started += instance.OnLight;
            @Light.performed += instance.OnLight;
            @Light.canceled += instance.OnLight;
            @Medium.started += instance.OnMedium;
            @Medium.performed += instance.OnMedium;
            @Medium.canceled += instance.OnMedium;
            @Heavy.started += instance.OnHeavy;
            @Heavy.performed += instance.OnHeavy;
            @Heavy.canceled += instance.OnHeavy;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="StandingActionsActions" />
        private void UnregisterCallbacks(IStandingActionsActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Light.started -= instance.OnLight;
            @Light.performed -= instance.OnLight;
            @Light.canceled -= instance.OnLight;
            @Medium.started -= instance.OnMedium;
            @Medium.performed -= instance.OnMedium;
            @Medium.canceled -= instance.OnMedium;
            @Heavy.started -= instance.OnHeavy;
            @Heavy.performed -= instance.OnHeavy;
            @Heavy.canceled -= instance.OnHeavy;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="StandingActionsActions.UnregisterCallbacks(IStandingActionsActions)" />.
        /// </summary>
        /// <seealso cref="StandingActionsActions.UnregisterCallbacks(IStandingActionsActions)" />
        public void RemoveCallbacks(IStandingActionsActions instance)
        {
            if (m_Wrapper.m_StandingActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="StandingActionsActions.AddCallbacks(IStandingActionsActions)" />
        /// <seealso cref="StandingActionsActions.RemoveCallbacks(IStandingActionsActions)" />
        /// <seealso cref="StandingActionsActions.UnregisterCallbacks(IStandingActionsActions)" />
        public void SetCallbacks(IStandingActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_StandingActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_StandingActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="StandingActionsActions" /> instance referencing this action map.
    /// </summary>
    public StandingActionsActions @StandingActions => new StandingActionsActions(this);

    // CrouchingActions
    private readonly InputActionMap m_CrouchingActions;
    private List<ICrouchingActionsActions> m_CrouchingActionsActionsCallbackInterfaces = new List<ICrouchingActionsActions>();
    private readonly InputAction m_CrouchingActions_CrouchLight;
    private readonly InputAction m_CrouchingActions_CrouchMedium;
    private readonly InputAction m_CrouchingActions_CrouchHeavy;
    /// <summary>
    /// Provides access to input actions defined in input action map "CrouchingActions".
    /// </summary>
    public struct CrouchingActionsActions
    {
        private @FighterController m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public CrouchingActionsActions(@FighterController wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "CrouchingActions/CrouchLight".
        /// </summary>
        public InputAction @CrouchLight => m_Wrapper.m_CrouchingActions_CrouchLight;
        /// <summary>
        /// Provides access to the underlying input action "CrouchingActions/CrouchMedium".
        /// </summary>
        public InputAction @CrouchMedium => m_Wrapper.m_CrouchingActions_CrouchMedium;
        /// <summary>
        /// Provides access to the underlying input action "CrouchingActions/CrouchHeavy".
        /// </summary>
        public InputAction @CrouchHeavy => m_Wrapper.m_CrouchingActions_CrouchHeavy;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_CrouchingActions; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="CrouchingActionsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(CrouchingActionsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="CrouchingActionsActions" />
        public void AddCallbacks(ICrouchingActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_CrouchingActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CrouchingActionsActionsCallbackInterfaces.Add(instance);
            @CrouchLight.started += instance.OnCrouchLight;
            @CrouchLight.performed += instance.OnCrouchLight;
            @CrouchLight.canceled += instance.OnCrouchLight;
            @CrouchMedium.started += instance.OnCrouchMedium;
            @CrouchMedium.performed += instance.OnCrouchMedium;
            @CrouchMedium.canceled += instance.OnCrouchMedium;
            @CrouchHeavy.started += instance.OnCrouchHeavy;
            @CrouchHeavy.performed += instance.OnCrouchHeavy;
            @CrouchHeavy.canceled += instance.OnCrouchHeavy;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="CrouchingActionsActions" />
        private void UnregisterCallbacks(ICrouchingActionsActions instance)
        {
            @CrouchLight.started -= instance.OnCrouchLight;
            @CrouchLight.performed -= instance.OnCrouchLight;
            @CrouchLight.canceled -= instance.OnCrouchLight;
            @CrouchMedium.started -= instance.OnCrouchMedium;
            @CrouchMedium.performed -= instance.OnCrouchMedium;
            @CrouchMedium.canceled -= instance.OnCrouchMedium;
            @CrouchHeavy.started -= instance.OnCrouchHeavy;
            @CrouchHeavy.performed -= instance.OnCrouchHeavy;
            @CrouchHeavy.canceled -= instance.OnCrouchHeavy;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CrouchingActionsActions.UnregisterCallbacks(ICrouchingActionsActions)" />.
        /// </summary>
        /// <seealso cref="CrouchingActionsActions.UnregisterCallbacks(ICrouchingActionsActions)" />
        public void RemoveCallbacks(ICrouchingActionsActions instance)
        {
            if (m_Wrapper.m_CrouchingActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="CrouchingActionsActions.AddCallbacks(ICrouchingActionsActions)" />
        /// <seealso cref="CrouchingActionsActions.RemoveCallbacks(ICrouchingActionsActions)" />
        /// <seealso cref="CrouchingActionsActions.UnregisterCallbacks(ICrouchingActionsActions)" />
        public void SetCallbacks(ICrouchingActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_CrouchingActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CrouchingActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="CrouchingActionsActions" /> instance referencing this action map.
    /// </summary>
    public CrouchingActionsActions @CrouchingActions => new CrouchingActionsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "StandingActions" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="StandingActionsActions.AddCallbacks(IStandingActionsActions)" />
    /// <seealso cref="StandingActionsActions.RemoveCallbacks(IStandingActionsActions)" />
    public interface IStandingActionsActions
    {
        /// <summary>
        /// Method invoked when associated input action "Movement" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMovement(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJump(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Crouch" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCrouch(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Light" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Medium" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMedium(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Heavy" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHeavy(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Dash" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDash(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "CrouchingActions" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="CrouchingActionsActions.AddCallbacks(ICrouchingActionsActions)" />
    /// <seealso cref="CrouchingActionsActions.RemoveCallbacks(ICrouchingActionsActions)" />
    public interface ICrouchingActionsActions
    {
        /// <summary>
        /// Method invoked when associated input action "CrouchLight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCrouchLight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CrouchMedium" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCrouchMedium(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CrouchHeavy" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCrouchHeavy(InputAction.CallbackContext context);
    }
}
